/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./src/assets/bread_pack.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/bread_pack.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.bread002.geometry} material={materials.bread01a} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={0.025} />
      <mesh geometry={nodes.bread003.geometry} material={materials.bread02a} position={[0.182, 0, 0]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={0.025} />
      <mesh geometry={nodes.bread.geometry} material={materials.bread03a} position={[-0.16, 0, 0]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={0.025} />
      <mesh geometry={nodes.bread001.geometry} material={materials.bread04a} position={[0.384, 0, 0]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={0.025} />
    </group>
  )
}

useGLTF.preload('/bread_pack.glb')
