/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\src\assets\WawaOffice.glb 
*/

import React, { useLayoutEffect, useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import gsap from 'gsap';
import { useFrame } from '@react-three/fiber';


export const FLOOR_HEIGHT = 3;
export const NB_FLOORS = 4;


export function Models(props) {



const { nodes, materials } = useGLTF('./src/assets/bread_pack.glb')
const ref = useRef(); // useRef é um React Hook que mantém um valor que nao é utilizado no render e permite referenciá-lo  
const tl = useRef(); // tl é uma referência que será utilizada adiante
const paoItaliano = useRef();
const paoFrances = useRef();
const paoFermnat = useRef();

useFrame( () => {
  tl.current.seek(scroll.offset * tl.current.duration()); 
});

useLayoutEffect( () => {

  tl.current = gsap.timeline(); // criamos um parâmetro em tl que é do tipo gsap.timeline(), que é utilizada para controlar as animações
  // // https://gsap.com/docs/v3/GSAP/gsap.timeline()/

  //VERTICAL ANIMATION
  tl.current.to(
      ref.current.position,
      {
          duration:3, 
          y: -FLOOR_HEIGHT * (NB_FLOORS - 1), 
      },
      0
  );
}, []
);


return (
  <group {...props} dispose={null}
  ref={ref}
  position={[-1.5,-1,-1]}
  rotation= {[0, -Math.PI/12,0]}
  >
    <mesh geometry={nodes.bread002.geometry} 
      material={materials.bread01a} 
      rotation={[-Math.PI / 3.0, 0, -Math.PI / 2]} 
      scale={0.25} 
    
    />
    <mesh geometry={nodes.bread003.geometry} 
      material={materials.bread02a} 
      position={[0, 3.5, 0]} 
      rotation={[-Math.PI / 3.5, 0, -Math.PI / 2]} 
      scale={0.25} 
    
    />
    <mesh geometry={nodes.bread.geometry} 
      material={materials.bread03a} 
      position={[0 , 6.5, 0]} 
      rotation={[-Math.PI / 3.5, 0, -Math.PI / 2]} 
      scale={0.25} 
    />
    <mesh geometry={nodes.bread001.geometry} 
      material={materials.bread04a} 
      position={[0, 9, 0]} 
      rotation={[-Math.PI / 3.5, 0, -Math.PI / 2]} 
      scale={0.25} 
    />
  </group>
  )

}

useGLTF.preload('./src/assets/bread_pack.glb')


// useGLTF.preload('./src/assets/italian_coffee_machine_moka.glb')
// useGLTF.preload('./src/assets/WawaOffice.glb')

// Assets CC Attribution:
// "FREE | Bread Pack (CS2)" (https://skfb.ly/oOIUZ) by 6lucius is licensed under Creative Commons Attribution (http://creativecommons.org/licenses/by/4.0/).